ENT.Base 			= "npc_vj_gf2_suomi"
ENT.Type 			= "ai"
ENT.PrintName 		= "Suomi (Midsummer Pixie)"
ENT.Author 			= "IBRS"
ENT.Contact 		= ""
ENT.Purpose 		= "Spawn it and fight with it!"
ENT.Instructions 	= "Click on the spawnicon to spawn it."
ENT.Category		= "Girls' Frontline 2"