
VJ.AddPlugin("Girls' Frontline 2: Exilium", "NPC","BETA")

local vCat = "#vj_gf2_snpcs.spawnmenu.Title"
local vCatUnf = "#vj_gf2_snpcs.spawnmenu.Title_Unf"
VJ.AddCategoryInfo(vCat, {Icon = "icons/gf2.png"})

VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Nemesis","npc_vj_gf2_nemesis",{"weapon_vj_gf2_om50"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Nemesis_Tactical","npc_vj_gf2_nemesis_tactical",{"weapon_vj_gf2_om50"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Nemesis_WanderingStarTrial","npc_vj_gf2_nemesis_wandering_star_trial",{"weapon_vj_gf2_om50"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Nemesis_SereneDarkRiver","npc_vj_gf2_nemesis_serene_dark_river",{"weapon_vj_gf2_om50"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Tololo","npc_vj_gf2_tololo",{"weapon_vj_gf2_ak_alfa"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Tololo_HorizonCruise","npc_vj_gf2_tololo_horizon_cruise",{"weapon_vj_gf2_ak_alfa"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Tololo_TwilightMilkyWay","npc_vj_gf2_tololo_twilight_milky_way",{"weapon_vj_gf2_ak_alfa"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Cheeta","npc_vj_gf2_cheeta",{"weapon_vj_gf2_mp7"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Cheeta_CircuitSparks","npc_vj_gf2_cheeta_circuit_sparks",{"weapon_vj_gf2_mp7"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Groza","npc_vj_gf2_groza",{"weapon_vj_gf2_ots14"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Groza_DawnOfBattle","npc_vj_gf2_groza_dawn_of_battle",{"weapon_vj_gf2_ots14"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Groza_VioletRain","npc_vj_gf2_groza_violet_rain",{"weapon_vj_gf2_ots14"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Groza_Tactical","npc_vj_gf2_groza_tactical",{"weapon_vj_gf2_ots14"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Peritya","npc_vj_gf2_peritya",{"weapon_vj_gf2_pkp_sp"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Peritya_BornHuntress","npc_vj_gf2_peritya_born_huntress",{"weapon_vj_gf2_pkp_sp"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Peritya_OperationPechenyan","npc_vj_gf2_peritya_operation_pechenyan",{"weapon_vj_gf2_pkp_sp"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Qiongjiu","npc_vj_gf2_qiongjiu",{"weapon_vj_gf2_qbz191"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Qiongjiu_BoundlessValor","npc_vj_gf2_qiongjiu_boundless_valor",{"weapon_vj_gf2_qbz191"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Nagant","npc_vj_gf2_nagant",{"weapon_vj_gf2_m1895_revolver"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Nagant_SummerPitcher","npc_vj_gf2_nagant_summer_pitcher",{"weapon_vj_gf2_m1895_revolver"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Suomi","npc_vj_gf2_suomi",{"weapon_vj_gf2_kp31"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Suomi_MidsummerPixie","npc_vj_gf2_suomi_midsummer_pixie",{"weapon_vj_gf2_kp31"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Suomi_FlurryKorvatunturi","npc_vj_gf2_suomi_flurry_korvatunturi",{"weapon_vj_gf2_kp31"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Sabrina","npc_vj_gf2_sabrina",{"weapon_vj_gf2_spas12"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Sabrina_BerryZabaione","npc_vj_gf2_sabrina_berry_zabaione",{"weapon_vj_gf2_spas12"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Mechty","npc_vj_gf2_mechty",{"weapon_vj_gf2_g11"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Vepley","npc_vj_gf2_vepley",{"weapon_vj_gf2_vepr_12"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Vepley_SparklingWish","npc_vj_gf2_vepley_sparkling_wish",{"weapon_vj_gf2_vepr_12"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Vepley_SummerEcho","npc_vj_gf2_vepley_summer_echo",{"weapon_vj_gf2_vepr_12"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Colphne","npc_vj_gf2_colphne",{"weapon_vj_gf2_taurus_curve"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Colphne_Tactical","npc_vj_gf2_colphne_tactical",{"weapon_vj_gf2_taurus_curve"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Colphne_SilentVoice","npc_vj_gf2_colphne_silent_voice",{"weapon_vj_gf2_taurus_curve"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Vector","npc_vj_gf2_vector",{"weapon_vj_gf2_kriss_vector"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Vector_ViviSometimesHidesHerMolotov","npc_vj_gf2_vector_vivi_sometimes_hides_her_molotov",{"weapon_vj_gf2_kriss_vector"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Vector_MolotovBunny","npc_vj_gf2_vector_molotov_bunny",{"weapon_vj_gf2_kriss_vector"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Lainie","npc_vj_gf2_lainie",{"weapon_vj_gf2_ump40"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Lainie_OperationButterfly","npc_vj_gf2_lainie_operation_butterfly",{"weapon_vj_gf2_ump40"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Lenna","npc_vj_gf2_lenna",{"weapon_vj_gf2_ump9"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Lenna_EnergeticMagic","npc_vj_gf2_lenna_energetic_magic",{"weapon_vj_gf2_ump9"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Lenna_FlyingPhantom","npc_vj_gf2_lenna_flying_phantom",{"weapon_vj_gf2_ump9"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Leva","npc_vj_gf2_leva",{"weapon_vj_gf2_ump45"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Leva_DiamondFlower","npc_vj_gf2_leva_diamond_flower",{"weapon_vj_gf2_ump45"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Jiangyu","npc_vj_gf2_jiangyu",{"weapon_vj_gf2_qbz97"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Jiangyu_RaindropCleavingBlades","npc_vj_gf2_jiangyu_raindrop_cleaving_blades",{"weapon_vj_gf2_qbz97"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Klukai","npc_vj_gf2_klukai",{"weapon_vj_gf2_hk416"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Klukai_AstralLuminous","npc_vj_gf2_klukai_astral_luminous",{"weapon_vj_gf2_hk416"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Klukai_SpeedStar","npc_vj_gf2_klukai_speed_star",{"weapon_vj_gf2_hk416"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Klukai_CeruleanBreaker","npc_vj_gf2_klukai_cerulean_breaker",{"weapon_vj_gf2_hk416"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Zhaohui","npc_vj_gf2_zhaohui",{"weapon_vj_gf2_csls06"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Zhaohui_RapidGrid","npc_vj_gf2_zhaohui_rapid_grid",{"weapon_vj_gf2_csls06"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Daiyan","npc_vj_gf2_daiyan",{"weapon_vj_gf2_qbz95"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Daiyan_ExquisiteJade","npc_vj_gf2_daiyan_exquisite_jade",{"weapon_vj_gf2_qbz95"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Ksenia","npc_vj_gf2_ksenia",{"weapon_vj_gf2_aps"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Faye","npc_vj_gf2_faye",{"weapon_vj_gf2_cz75"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Faye_FlurryCrimson","npc_vj_gf2_faye_flurry_crimson",{"weapon_vj_gf2_cz75"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Sharkry","npc_vj_gf2_sharkry",{"weapon_vj_gf2_xcr"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Sharkry_SwimsuitIdol","npc_vj_gf2_sharkry_swimsuit_idol",{"weapon_vj_gf2_xcr"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Centaureissi","npc_vj_gf2_centaureissi",{"weapon_vj_gf2_g36"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Centaureissi_50DaysWithReissi","npc_vj_gf2_centaureissi_50_days_with_reissi",{"weapon_vj_gf2_g36"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Dushevnaya","npc_vj_gf2_dushevnaya",{"weapon_vj_gf2_ksvk"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Robella","npc_vj_gf2_robella",{"weapon_vj_gf2_ro635"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Robella_FutureNavigator","npc_vj_gf2_robella_future_navigator",{"weapon_vj_gf2_ro635"},vCatUnf)
--VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Robella_Skin2","npc_vj_gf2_robella_skin2",{"weapon_vj_gf2_ro635"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Charolic","npc_vj_gf2_charolic",{"weapon_vj_gf2_blade"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Charolic_LeapingRabbit","npc_vj_gf2_charolic_leaping_rabbit",{"weapon_vj_gf2_blade"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Charolic_Tactical","npc_vj_gf2_charolic_tactical",{"weapon_vj_gf2_blade"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Papasha","npc_vj_gf2_papasha",{"weapon_vj_gf2_ppsh41"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Florence","npc_vj_gf2_florence",{"weapon_vj_gf2_pa15"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Florence_MarvelousYamPastry","npc_vj_gf2_florence_marvelous_yam_pastry",{"weapon_vj_gf2_pa15"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Varjager_Soldier","npc_vj_gf2_varjager_soldier",{"weapon_vj_gf2_varjager_ak101","weapon_vj_gf2_varjager_ak74","weapon_vj_gf2_varjager_akm_plam"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Varjager_Medic","npc_vj_gf2_varjager_medic",{"weapon_vj_glock17","weapon_vj_gf2_varjager_aks74u","weapon_vj_gf2_varjager_akmsu"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Varjager_Warrior","npc_vj_gf2_varjager_warrior",{"weapon_vj_gf2_varjager_axe","weapon_vj_gf2_varjager_mpl40","weapon_vj_gf2_varjager_taiga"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Varjager_Sniper","npc_vj_gf2_varjager_sniper",{"weapon_vj_gf2_varjager_mosin"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Varjager_Heavy","npc_vj_gf2_varjager_heavy",{"weapon_vj_rpg","weapon_vj_spas12","weapon_vj_gf2_varjager_akm_drum","weapon_vj_gf2_varjager_rpd"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Andoris","npc_vj_gf2_andoris",{"weapon_vj_gf2_g36k"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Andoris_MidnightWhispers","npc_vj_gf2_andoris_midnight_whispers",{"weapon_vj_gf2_g36k"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Lind","npc_vj_gf2_lind",{"weapon_vj_gf2_aa12"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Lind_TheSunNeverRises","npc_vj_gf2_lind_the_sun_never_rises",{"weapon_vj_gf2_aa12"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Alva","npc_vj_gf2_alva",{"weapon_vj_gf2_an94"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Alva_Antje","npc_vj_gf2_alva_antje",{"weapon_vj_gf2_an94"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Ullrid","npc_vj_gf2_ullrid",{"weapon_vj_gf2_feathered_edge"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Belka","npc_vj_gf2_belka",{"weapon_vj_gf2_g28"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Belka_EnigmaticPhantomsDream","npc_vj_gf2_belka_enigmatic_phantoms_dream",{"weapon_vj_gf2_g28"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Littara","npc_vj_gf2_littara",{"weapon_vj_gf2_galil_arm"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Lotta","npc_vj_gf2_lotta",{"weapon_vj_gf2_m1_super90"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Lotta_RookieAthlete","npc_vj_gf2_lotta_rookie_athlete",{"weapon_vj_gf2_m1_super90"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Macqiato","npc_vj_gf2_macqiato",{"weapon_vj_gf2_wa2000"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Macqiato_BallroomInterlude","npc_vj_gf2_macqiato_ballroom_interlude",{"weapon_vj_gf2_wa2000"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Macqiato_BlossomingShadows","npc_vj_gf2_macqiato_blossoming_shadows",{"weapon_vj_gf2_wa2000"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Macqiato_HotSpringHolidays","npc_vj_gf2_macqiato_hot_spring_holidays",{"weapon_vj_gf2_wa2000"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.MosinNagant","npc_vj_gf2_mosin_nagant",{"weapon_vj_gf2_m1891"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.MosinNagant_SiberianSlide","npc_vj_gf2_mosin_nagant_siberian_slide",{"weapon_vj_gf2_m1891"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Nikketa","npc_vj_gf2_nikketa",{"weapon_vj_gf2_vsk94"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Nikketa_BlazingSunDance","npc_vj_gf2_nikketa_blazing_sun_dance",{"weapon_vj_gf2_vsk94"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Nikketa_NightOnTheSilverBay","npc_vj_gf2_nikketa_night_on_the_silver_bay",{"weapon_vj_gf2_vsk94"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Peri","npc_vj_gf2_peri",{"weapon_vj_gf2_mp5"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Qiuhua","npc_vj_gf2_qiuhua",{"weapon_vj_gf2_hawk_type97"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Qiuhua_CompassionAndCare","npc_vj_gf2_qiuhua_compassion_and_care",{"weapon_vj_gf2_hawk_type97"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Qiuhua_AutumnBanquetChef","npc_vj_gf2_qiuhua_autumn_banquet_chef",{"weapon_vj_gf2_hawk_type97"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Springfield","npc_vj_gf2_springfield",{"weapon_vj_gf2_m1903"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Springfield_EnjoyTheFragrance","npc_vj_gf2_springfield_enjoy_the_fragrance",{"weapon_vj_gf2_m1903"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Springfield_QueenInRadiance","npc_vj_gf2_springfield_queen_in_radiance",{"weapon_vj_gf2_m1903"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Yoohee","npc_vj_gf2_yoohee",{"weapon_vj_gf2_k2"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Yoohee_MiracleSweetheart","npc_vj_gf2_yoohee_miracle_sweetheart",{"weapon_vj_gf2_k2"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Balthilde","npc_vj_gf2_balthilde",{"weapon_vj_gf2_ls26"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Voymastina","npc_vj_gf2_voymastina",{"weapon_vj_gf2_ak15"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Voymastina_Erwin","npc_vj_gf2_voymastina_erwin",{"weapon_vj_gf2_ak15"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Lewis","npc_vj_gf2_lewis",{"weapon_vj_gf2_lewis_gun"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Lewis_Sunscreen_Battle","npc_vj_gf2_lewis_sunscreen_battle",{"weapon_vj_gf2_lewis_gun"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Helen","npc_vj_gf2_helen",{"weapon_vj_gf2_dp12"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Helen_StarlitWaltz","npc_vj_gf2_helen_starlit_waltz",{"weapon_vj_gf2_dp12"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Harpsy","npc_vj_gf2_harpsy",{"weapon_vj_gf2_tmp"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Loreley","npc_vj_gf2_loreley",{"weapon_vj_gf2_dsr50"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Loreley_TwilightWhisper","npc_vj_gf2_loreley_twilight_whisper",{"weapon_vj_gf2_dsr50"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Cheyanne","npc_vj_gf2_cheyanne",{"weapon_vj_gf2_m200"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Cheyanne_MaidenDebut","npc_vj_gf2_cheyanne_maiden_debut",{"weapon_vj_gf2_m200"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Sakura","npc_vj_gf2_sakura",{"weapon_vj_gf2_type100"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Sakura_TaleOfTheButterflies","npc_vj_gf2_sakura_tale_of_the_butterflies",{"weapon_vj_gf2_type100"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Phaetusa","npc_vj_gf2_phaetusa",{"weapon_vj_gf2_cinderthorn"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Phaetusa_EternalNightGarden","npc_vj_gf2_phaetusa_eternal_night_garden",{"weapon_vj_gf2_cinderthorn"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Basti","npc_vj_gf2_basti",{"weapon_vj_gf2_mk23"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Basti_PeachSoda","npc_vj_gf2_basti_peach_soda",{"weapon_vj_gf2_mk23"},vCatUnf)

VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Arges","npc_vj_gf2_arges",{"weapon_vj_gf2_arges_smg"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Brontes","npc_vj_gf2_brontes",{"weapon_vj_gf2_brontes_shotgun"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Jord","npc_vj_gf2_jord",{"weapon_vj_gf2_jord_flamethrower"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Steropes","npc_vj_gf2_steropes",{"weapon_vj_gf2_steropes_rifle"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Surtr","npc_vj_gf2_surtr",{"weapon_vj_gf2_surtr_weapon1","weapon_vj_gf2_surtr_weapon2"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Unknown_Groza","npc_vj_gf2_unknown_groza",{"weapon_vj_gf2_unknown_groza_weapon"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Scout_Vanguard","npc_vj_gf2_scout_vanguard",{"weapon_vj_flaregun"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Sextans","npc_vj_gf2_sextans",{"weapon_vj_gf2_sextans_revolver","weapon_vj_gf2_sextans_flintlock"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Lose_Sextans","npc_vj_gf2_lose_sextans",{"weapon_vj_gf2_lose_sextans_cannon"},vCatUnf)

VJ.AddNPC("#vj_gf2_snpcs.Golyat","npc_vj_gf2_golyat_base",vCat)
VJ.AddNPC("#vj_gf2_snpcs.Golyat_Electric","npc_vj_gf2_golyat_electric",vCatUnf)
VJ.AddNPC("#vj_gf2_snpcs.Golyat_Red","npc_vj_gf2_golyat_red",vCat)
VJ.AddNPC("#vj_gf2_snpcs.Golyat_Football","npc_vj_gf2_golyat_football",vCat)
VJ.AddNPC("#vj_gf2_snpcs.Golyat_Fire","npc_vj_gf2_golyat_fire",vCatUnf)
VJ.AddNPC("#vj_gf2_snpcs.Golyat_Ice","npc_vj_gf2_golyat_ice",vCatUnf)
VJ.AddNPC("#vj_gf2_snpcs.Blusphere", "npc_vj_gf2_blusphere",vCatUnf)
VJ.AddNPC("#vj_gf2_snpcs.Deichgraf", "npc_vj_gf2_deichgraf",vCatUnf)

-- Weapons
VJ.AddNPCWeapon("#weapon_vj_gf2_om50", "weapon_vj_gf2_om50", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_ak_alfa", "weapon_vj_gf2_ak_alfa", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_mp7", "weapon_vj_gf2_mp7", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_ots14", "weapon_vj_gf2_ots14", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_m1895_revolver", "weapon_vj_gf2_m1895_revolver", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_pkp_sp", "weapon_vj_gf2_pkp_sp", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_qbz191", "weapon_vj_gf2_qbz191", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_spas12", "weapon_vj_gf2_spas12", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_vepr_12", "weapon_vj_gf2_vepr_12", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_g11", "weapon_vj_gf2_g11", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_taurus_curve", "weapon_vj_gf2_taurus_curve", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_kriss_vector", "weapon_vj_gf2_kriss_vector", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_ump9", "weapon_vj_gf2_ump9", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_ump40", "weapon_vj_gf2_ump40", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_ump45", "weapon_vj_gf2_ump45", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_kp31", "weapon_vj_gf2_kp31", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_qbz97", "weapon_vj_gf2_qbz97", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_hk416", "weapon_vj_gf2_hk416", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_csls06", "weapon_vj_gf2_csls06", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_qbz95", "weapon_vj_gf2_qbz95", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_aps", "weapon_vj_gf2_aps", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_cz75", "weapon_vj_gf2_cz75", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_wa2000", "weapon_vj_gf2_wa2000", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_xcr", "weapon_vj_gf2_xcr", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_k2", "weapon_vj_gf2_k2", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_vsk94", "weapon_vj_gf2_vsk94", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_ro635", "weapon_vj_gf2_ro635", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_ppsh41", "weapon_vj_gf2_ppsh41", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_mp5", "weapon_vj_gf2_mp5", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_m1903", "weapon_vj_gf2_m1903", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_m1891", "weapon_vj_gf2_m1891", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_m1_super90", "weapon_vj_gf2_m1_super90", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_ksvk", "weapon_vj_gf2_ksvk", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_hawk_type97", "weapon_vj_gf2_hawk_type97", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_galil_arm", "weapon_vj_gf2_galil_arm", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_g36k", "weapon_vj_gf2_g36k", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_g36", "weapon_vj_gf2_g36", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_pa15", "weapon_vj_gf2_pa15", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_aa12", "weapon_vj_gf2_aa12", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_an94", "weapon_vj_gf2_an94", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_ak15", "weapon_vj_gf2_ak15", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_ls26", "weapon_vj_gf2_ls26", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_lewis_gun", "weapon_vj_gf2_lewis_gun", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_dp12", "weapon_vj_gf2_dp12", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_blade", "weapon_vj_gf2_blade", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_feathered_edge", "weapon_vj_gf2_feathered_edge", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_g28", "weapon_vj_gf2_g28", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_type100", "weapon_vj_gf2_type100", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_m200", "weapon_vj_gf2_m200", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_tmp", "weapon_vj_gf2_tmp", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_dsr50", "weapon_vj_gf2_dsr50", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_cinderthorn", "weapon_vj_gf2_cinderthorn", vCat)
VJ.AddNPCWeapon("#weapon_vj_gf2_mk23", "weapon_vj_gf2_mk23", vCat)

VJ.AddNPCWeapon("#vj_gf2_snpcs.weapon_plasma_cannon", "weapon_vj_gf2_lose_sextans_cannon", vCat)
VJ.AddNPCWeapon("#vj_gf2_snpcs.weapon_pulse_rifle", "weapon_vj_gf2_unknown_groza_weapon", vCat)
VJ.AddNPCWeapon("#vj_gf2_snpcs.weapon_pulse_smg", "weapon_vj_gf2_arges_smg", vCat)
VJ.AddNPCWeapon("#vj_gf2_snpcs.weapon_pulse_shotgun", "weapon_vj_gf2_brontes_shotgun", vCat)
VJ.AddNPCWeapon("#vj_gf2_snpcs.weapon_pulse_rifle", "weapon_vj_gf2_steropes_rifle", vCat)
VJ.AddNPCWeapon("#vj_gf2_snpcs.weapon_pulse_rifle", "weapon_vj_gf2_surtr_weapon1", vCat)
VJ.AddNPCWeapon("#vj_gf2_snpcs.weapon_pulse_shotgun", "weapon_vj_gf2_surtr_weapon2", vCat)
VJ.AddNPCWeapon("Flamethrower", "weapon_vj_gf2_jord_flamethrower", vCat)

VJ.AddNPCWeapon("AK-101", "weapon_vj_gf2_varjager_ak101", vCat)
VJ.AddNPCWeapon("AK-74", "weapon_vj_gf2_varjager_ak74", vCat)
VJ.AddNPCWeapon("AKM (Drum)", "weapon_vj_gf2_varjager_akm_drum", vCat)
VJ.AddNPCWeapon("AKM (Plam)", "weapon_vj_gf2_varjager_akm_plam", vCat)
VJ.AddNPCWeapon("AKM-SU", "weapon_vj_gf2_varjager_akmsu", vCat)
VJ.AddNPCWeapon("RPD", "weapon_vj_gf2_varjager_rpd", vCat)
VJ.AddNPCWeapon("AKS-74U", "weapon_vj_gf2_varjager_aks74u", vCat)
VJ.AddNPCWeapon("Mosin", "weapon_vj_gf2_varjager_mosin", vCat)
VJ.AddNPCWeapon("Axe", "weapon_vj_gf2_varjager_axe", vCat)
VJ.AddNPCWeapon("MPL40", "weapon_vj_gf2_varjager_mpl40", vCat)
VJ.AddNPCWeapon("Taiga", "weapon_vj_gf2_varjager_taiga", vCat)

VJ.AddNPCWeapon("#vj_gf2_snpcs.weapon_klukai_axe", "weapon_vj_gf2_klukai_axe", vCat)

VJ.AddEntity("#vj_gf2_items.Colphne_Healthkit", "sent_gf2_colphne_healthkit", "IBRS", false, 0, true, vCat)
VJ.AddEntity("#vj_gf2_items.Colphne_Syringe", "sent_gf2_colphne_syringe", "IBRS", false, 0, true, vCat)
VJ.AddEntity("#vj_gf2_items.Colphne_Bandage", "sent_gf2_colphne_bandage", "IBRS", false, 0, true, vCat)
if (file.Exists( "entities/sent_gf2_musicbox.lua", "LUA" )) then
VJ.AddEntity("#vj_gf2_ents.Music_Box", "sent_gf2_musicbox", "IBRS", false, 0, true, vCat)
end

-- Precache Models --
-- Grenade Models
util.PrecacheModel("models/prop/gfl2_cheeta_lollipop_grenade.mdl")
util.PrecacheModel("models/prop/gfl2_peritya_grenade.mdl")
util.PrecacheModel("models/prop/gfl2_vector_incendiary_grenade.mdl")

-- Misc Models
util.PrecacheModel("models/prop/gfl2_cheeta_lollipop_1.mdl")
util.PrecacheModel("models/prop/gfl2_cheeta_lollipop_2.mdl")
util.PrecacheModel("models/prop/gfl2_cheeta_lollipop_3.mdl")
util.PrecacheModel("models/prop/gfl2_colphne_bandage.mdl")
util.PrecacheModel("models/prop/gfl2_colphne_medkit.mdl")
util.PrecacheModel("models/prop/gfl2_colphne_syringe.mdl")
util.PrecacheModel("models/prop/gfl2_mechty_energy_drink.mdl")

-- ConVars --
VJ.AddConVar("vj_gf2_varjager_h",250)
VJ.AddConVar("vj_gf2_varjager_d",25)

-- AR
VJ.AddConVar("vj_gf2_tololo_h",300)
VJ.AddConVar("vj_gf2_tololo_d",60)
VJ.AddConVar("vj_gf2_groza_h",300)
VJ.AddConVar("vj_gf2_groza_d",70)
VJ.AddConVar("vj_gf2_qiongjiu_h",300)
VJ.AddConVar("vj_gf2_qiongjiu_d",60)
VJ.AddConVar("vj_gf2_mechty_h",450)
VJ.AddConVar("vj_gf2_mechty_d",20)
VJ.AddConVar("vj_gf2_jiangyu_h",250)
VJ.AddConVar("vj_gf2_jiangyu_d",50)
VJ.AddConVar("vj_gf2_klukai_h",300)
VJ.AddConVar("vj_gf2_klukai_d",60)
VJ.AddConVar("vj_gf2_daiyan_h",300)
VJ.AddConVar("vj_gf2_daiyan_d",80)
VJ.AddConVar("vj_gf2_sharkry_h",225)
VJ.AddConVar("vj_gf2_sharkry_d",25)
VJ.AddConVar("vj_gf2_centaureissi_h",300)
VJ.AddConVar("vj_gf2_centaureissi_d",30)
VJ.AddConVar("vj_gf2_andoris_h",250)
VJ.AddConVar("vj_gf2_andoris_d",25)
VJ.AddConVar("vj_gf2_alva_h",375)
VJ.AddConVar("vj_gf2_alva_d",35)
VJ.AddConVar("vj_gf2_belka_h",225)
VJ.AddConVar("vj_gf2_belka_d",25)
VJ.AddConVar("vj_gf2_yoohee_h",425)
VJ.AddConVar("vj_gf2_yoohee_d",50)
VJ.AddConVar("vj_gf2_voymastina_h",550)
VJ.AddConVar("vj_gf2_voymastina_d",150)

-- SMG
VJ.AddConVar("vj_gf2_cheeta_h",250)
VJ.AddConVar("vj_gf2_cheeta_d",50)
VJ.AddConVar("vj_gf2_suomi_h",400)
VJ.AddConVar("vj_gf2_suomi_d",20)
VJ.AddConVar("vj_gf2_vector_h",300)
VJ.AddConVar("vj_gf2_vector_d",60)
VJ.AddConVar("vj_gf2_lenna_h",300)
VJ.AddConVar("vj_gf2_lenna_d",60)
VJ.AddConVar("vj_gf2_lainie_h",325)
VJ.AddConVar("vj_gf2_lainie_d",70)
VJ.AddConVar("vj_gf2_leva_h",350)
VJ.AddConVar("vj_gf2_leva_d",80)
VJ.AddConVar("vj_gf2_zhaohui_h",350)
VJ.AddConVar("vj_gf2_zhaohui_d",40)
VJ.AddConVar("vj_gf2_robella_h",275)
VJ.AddConVar("vj_gf2_robella_d",25)
VJ.AddConVar("vj_gf2_papasha_h",250)
VJ.AddConVar("vj_gf2_papasha_d",50)
VJ.AddConVar("vj_gf2_peri_h",275)
VJ.AddConVar("vj_gf2_peri_d",30)
VJ.AddConVar("vj_gf2_harpsy_h",250)
VJ.AddConVar("vj_gf2_harpsy_d",30)
VJ.AddConVar("vj_gf2_sakura_h",225)
VJ.AddConVar("vj_gf2_sakura_d",25)

-- RF
VJ.AddConVar("vj_gf2_nemesis_h",200)
VJ.AddConVar("vj_gf2_nemesis_d",40)
VJ.AddConVar("vj_gf2_dushevnaya_h",225)
VJ.AddConVar("vj_gf2_dushevnaya_d",45)
VJ.AddConVar("vj_gf2_macqiato_h",275)
VJ.AddConVar("vj_gf2_macqiato_d",35)
VJ.AddConVar("vj_gf2_mosin_nagant_h",250)
VJ.AddConVar("vj_gf2_mosin_nagant_d",30)
VJ.AddConVar("vj_gf2_nikketa_h",225)
VJ.AddConVar("vj_gf2_nikketa_d",35)
VJ.AddConVar("vj_gf2_springfield_h",300)
VJ.AddConVar("vj_gf2_springfield_d",25)
VJ.AddConVar("vj_gf2_loreley_h",250)
VJ.AddConVar("vj_gf2_loreley_d",25)
VJ.AddConVar("vj_gf2_cheyanne_h",300)
VJ.AddConVar("vj_gf2_cheyanne_d",40)

-- SG
VJ.AddConVar("vj_gf2_sabrina_h",350)
VJ.AddConVar("vj_gf2_sabrina_d",40)
VJ.AddConVar("vj_gf2_vepley_h",300)
VJ.AddConVar("vj_gf2_vepley_d",75)
VJ.AddConVar("vj_gf2_lind_h",200)
VJ.AddConVar("vj_gf2_lind_d",25)
VJ.AddConVar("vj_gf2_lotta_h",350)
VJ.AddConVar("vj_gf2_lotta_d",70)
VJ.AddConVar("vj_gf2_qiuhua_h",375)
VJ.AddConVar("vj_gf2_qiuhua_d",90)
VJ.AddConVar("vj_gf2_helen_h",400)
VJ.AddConVar("vj_gf2_helen_d",50)

-- MG
VJ.AddConVar("vj_gf2_peritya_h",500)
VJ.AddConVar("vj_gf2_peritya_d",25)
VJ.AddConVar("vj_gf2_littara_h",300)
VJ.AddConVar("vj_gf2_littara_d",50)
VJ.AddConVar("vj_gf2_balthilde_h",450)
VJ.AddConVar("vj_gf2_balthilde_d",50)
VJ.AddConVar("vj_gf2_lewis_h",350)
VJ.AddConVar("vj_gf2_lewis_d",25)

-- HG
VJ.AddConVar("vj_gf2_nagant_h",250)
VJ.AddConVar("vj_gf2_nagant_d",25)
VJ.AddConVar("vj_gf2_colphne_h",200)
VJ.AddConVar("vj_gf2_colphne_d",15)
VJ.AddConVar("vj_gf2_ksenia_h",250)
VJ.AddConVar("vj_gf2_ksenia_d",25)
VJ.AddConVar("vj_gf2_faye_h",275)
VJ.AddConVar("vj_gf2_faye_d",30)
VJ.AddConVar("vj_gf2_florence_h",225)
VJ.AddConVar("vj_gf2_florence_d",15)
VJ.AddConVar("vj_gf2_basti_h",250)
VJ.AddConVar("vj_gf2_basti_d",20)

-- Melee
VJ.AddConVar("vj_gf2_charolic_h",350)
VJ.AddConVar("vj_gf2_charolic_d",75)
VJ.AddConVar("vj_gf2_ullrid_h",400)
VJ.AddConVar("vj_gf2_ullrid_d",100)
VJ.AddConVar("vj_gf2_phaetusa_h",375)
VJ.AddConVar("vj_gf2_phaetusa_d",75)

-- Others
VJ.AddConVar("vj_gf2_unknown_groza_h",1250)
VJ.AddConVar("vj_gf2_unknown_groza_d",250)
VJ.AddConVar("vj_gf2_sextans_h",1500)
VJ.AddConVar("vj_gf2_sextans_d",100)
VJ.AddConVar("vj_gf2_lose_sextans_h",3000)
VJ.AddConVar("vj_gf2_lose_sextans_d",200)

VJ.AddConVar("vj_gf2_scout_vanguard_h",250)
VJ.AddConVar("vj_gf2_scout_vanguard_d",50)

VJ.AddConVar("vj_gf2_arges_h",750)
VJ.AddConVar("vj_gf2_arges_d",150)
VJ.AddConVar("vj_gf2_brontes_h",750)
VJ.AddConVar("vj_gf2_brontes_d",150)
VJ.AddConVar("vj_gf2_steropes_h",750)
VJ.AddConVar("vj_gf2_steropes_d",150)
VJ.AddConVar("vj_gf2_surtr_h",750)
VJ.AddConVar("vj_gf2_surtr_d",150)
VJ.AddConVar("vj_gf2_jord_h",750)
VJ.AddConVar("vj_gf2_jord_d",150)

-- Weapons
-- AR
VJ.AddConVar("vj_gf2_ak_alfa_d",40)
VJ.AddConVar("vj_gf2_ots14_d",60)
VJ.AddConVar("vj_gf2_qbz191_d",50)
VJ.AddConVar("vj_gf2_g11_d",25)
VJ.AddConVar("vj_gf2_qbz97_d",40)
VJ.AddConVar("vj_gf2_hk416_d",45)
VJ.AddConVar("vj_gf2_qbz95_d",55)
VJ.AddConVar("vj_gf2_xcr_d",40)
VJ.AddConVar("vj_gf2_g36_d",30)
VJ.AddConVar("vj_gf2_an94_d",40)
VJ.AddConVar("vj_gf2_g28_d",75)
VJ.AddConVar("vj_gf2_g36k_d",30)
VJ.AddConVar("vj_gf2_k2_d",35)
VJ.AddConVar("vj_gf2_ak15_d",65)
VJ.AddConVar("vj_gf2_unknown_groza_weapon_d",75)

-- RF
VJ.AddConVar("vj_gf2_om50_d",150)
VJ.AddConVar("vj_gf2_wa2000_d",125)
VJ.AddConVar("vj_gf2_ksvk_d",250)
VJ.AddConVar("vj_gf2_vsk94_d",80)
VJ.AddConVar("vj_gf2_m1891_d",160)
VJ.AddConVar("vj_gf2_m1903_d",180)
VJ.AddConVar("vj_gf2_dsr50_d",450)
VJ.AddConVar("vj_gf2_m200_d",300)

-- SMG
VJ.AddConVar("vj_gf2_mp7_d",25)
VJ.AddConVar("vj_gf2_kriss_vector_d",30)
VJ.AddConVar("vj_gf2_ump9_d",30)
VJ.AddConVar("vj_gf2_ump40_d",35)
VJ.AddConVar("vj_gf2_ump45_d",40)
VJ.AddConVar("vj_gf2_kp31_d",25)
VJ.AddConVar("vj_gf2_csls06_d",30)
VJ.AddConVar("vj_gf2_mp5_d",30)
VJ.AddConVar("vj_gf2_ppsh41_d",25)
VJ.AddConVar("vj_gf2_ro635_d",40)
VJ.AddConVar("vj_gf2_tmp_d",30)
VJ.AddConVar("vj_gf2_type100_d",25)

-- SG
VJ.AddConVar("vj_gf2_spas12_d",40)
VJ.AddConVar("vj_gf2_vepr_12_d",25)
VJ.AddConVar("vj_gf2_aa12_d",35)
VJ.AddConVar("vj_gf2_hawk_type97_d",45)
VJ.AddConVar("vj_gf2_m1_super90_d",40)
VJ.AddConVar("vj_gf2_dp12_d",30)

-- HG
VJ.AddConVar("vj_gf2_m1895_revolver_d",75)
VJ.AddConVar("vj_gf2_taurus_curve_d",15)
VJ.AddConVar("vj_gf2_aps_d",15)
VJ.AddConVar("vj_gf2_cz75_d",20)
VJ.AddConVar("vj_gf2_pa15_d",15)
VJ.AddConVar("vj_gf2_mk23_d",20)

-- MG
VJ.AddConVar("vj_gf2_galil_arm_d",40)
VJ.AddConVar("vj_gf2_ls26_d",50)
VJ.AddConVar("vj_gf2_pkp_sp_d",75)
VJ.AddConVar("vj_gf2_lewis_gun_d",35)

-- Other
VJ.AddConVar("vj_gf2_lose_sextans_cannon_d",250)

VJ.AddConVar("vj_gf2_arges_smg_d",35)
VJ.AddConVar("vj_gf2_steropes_rifle_d",250)
VJ.AddConVar("vj_gf2_brontes_shotgun_d",20)
VJ.AddConVar("vj_gf2_surtr_weapon1_d",45)
VJ.AddConVar("vj_gf2_surtr_weapon2_d",15)

-- Menu --
local AddConvars = {}
AddConvars["vj_gf2_drop_magazines"] = 1 -- Drop magazines?
AddConvars["vj_gf2_magazineremovetime"] = 15 -- Magazine remove time.
AddConvars["vj_gf2_death_expressions"] = 1 -- Death expressions?
AddConvars["vj_gf2_death_fingerpose"] = 1 -- Death finger pose?
AddConvars["vj_gf2_npc_random_bodygroups"] = 1 -- Random bodygroup for SNPCs?
AddConvars["vj_gf2_npc_shield_multipler"] = 1 -- Shield multipler.
AddConvars["vj_gf2_npc_shield_radius_multipler"] = 1 -- Shield radius multipler.
AddConvars["vj_gf2_npc_shield"] = 1 -- Enable shield.
AddConvars["vj_gf2_npc_shield_ricochet"] = 1 -- Shield can ricochet bullets.
AddConvars["vj_gf2_npc_shield_ricochet_chance"] = 10 -- Shield ricochet chance.
AddConvars["vj_gf2_npc_shield_ricochet_damage_scale"] = 0.25 -- Shield ricochet bullets damage scale.
AddConvars["vj_gf2_npc_shield_exceed_maxhealth"] = 0 -- Shield can exceed max health.
AddConvars["vj_gf2_npc_element_electric_enabled"] = 1 -- Enable electric effects.
AddConvars["vj_gf2_npc_element_electric_damage_multipler"] = 1 -- Electric damage multipler.
AddConvars["vj_gf2_npc_element_electric_radius_multipler"] = 1 -- Electric radius multipler.
AddConvars["vj_gf2_npc_element_freezing_enabled"] = 1 -- Enable freezing effects.
AddConvars["vj_gf2_npc_element_freezing_radius_multipler"] = 1 -- Freezing radius multipler.
AddConvars["vj_gf2_npc_element_fire_enabled"] = 1 -- Enable fire effects.
AddConvars["vj_gf2_npc_element_acid_enabled"] = 1 -- Enable acid effects.
AddConvars["vj_gf2_npc_element_acid_time_multipler"] = 1 -- Acid time multipler.
AddConvars["vj_gf2_npc_element_acid_damage_multipler"] = 0.1 -- Acid damage multipler.
AddConvars["vj_gf2_npc_element_water_enabled"] = 1 -- Enable water effects.
AddConvars["vj_gf2_npc_element_water_hp_reduce_rate"] = 0.01 -- Enable water effects.
AddConvars["vj_gf2_infinite_ammo"] = 0 -- Infinite ammo.
AddConvars["vj_gf2_bullet_damage_multipler"] = 1 -- Bullet multiplier.
AddConvars["vj_gf2_speed_modifier"] = 1 -- Speed modifier.
AddConvars["vj_gf2_animation_speed_modifier"] = 1 -- Animation modifier.
AddConvars["vj_gf2_npc_find_cover_on_reload"] = 1 -- Find cover on reload.
AddConvars["vj_gf2_npc_use_pose_parameter_movement"] = 0 -- Use pose parameter movement.
AddConvars["vj_gf2_npc_charolic_ignite_target"] = 1 -- Charolic ignite targets.
AddConvars["vj_gf2_npc_leva_hacking"] = 1 -- Leva hacking.
AddConvars["vj_gf2_npc_golyat_damage_friendly"] = 1 -- Golyat deals damage to all NPCs.
AddConvars["vj_gf2_npc_deichgraf_missile_count"] = 6 -- How many missiles to launch in a roll.
AddConvars["vj_gf2_npc_voice_language"] = "jp" -- Voice language.
AddConvars["vj_gf2_npc_drop_weapon_on_death"] = 0 -- Drop weapon on death.
AddConvars["vj_gf2_npc_drop_item_on_death"] = 0 -- Drop weapon on death.

for k, v in pairs(AddConvars) do
	if !ConVarExists( k ) then CreateConVar( k, v, {FCVAR_ARCHIVE} ) end
end

VJ.AddClientConVar("vj_gf2_draw_shield", 1, "Draw Shield.")
VJ.AddClientConVar("vj_gf2_attachment_draw_laser", 1, "Draw Laser.")
VJ.AddClientConVar("vj_gf2_draw_bullets", 1, "Draw Bullets.")

if CLIENT then
	hook.Add( "PopulateToolMenu", "VJ_ADDTOMENU_GF2", function()
		spawnmenu.AddToolMenuOption( "DrVrej", "SNPC Configures", "Girls' Frontline 2: Exilium", "#vj_gf2_snpcs.settings.Title", "", "", function(Panel) 
			if game.SinglePlayer() or LocalPlayer():IsAdmin() then
				Panel:Help("#vjbase.menu.general.admin.only")
				Panel:CheckBox("#vj_gf2_snpcs.settings.DropMagazines", "vj_gf2_drop_magazines")
				Panel:ControlHelp("#vj_gf2_snpcs.settings.DropMagazines.Desc")
				Panel:NumSlider("#vj_gf2_snpcs.settings.MagazineRemoveTimer", "vj_gf2_magazineremovetime", 5, 60, 0)
				Panel:ControlHelp("#vj_gf2_snpcs.settings.MagazineRemoveTimer.Desc")
				Panel:CheckBox("#vj_gf2_snpcs.settings.DropWeapon", "vj_gf2_npc_drop_weapon_on_death")
				Panel:CheckBox("#vj_gf2_snpcs.settings.DropItem", "vj_gf2_npc_drop_item_on_death")
				Panel:CheckBox("#vj_gf2_snpcs.settings.DeathExpressions", "vj_gf2_death_expressions")
				Panel:CheckBox("#vj_gf2_snpcs.settings.DeathFingerPose", "vj_gf2_death_fingerpose")
				Panel:CheckBox("#vj_gf2_snpcs.settings.NPC_RandomBodygroups", "vj_gf2_npc_random_bodygroups")
				Panel:CheckBox("#vj_gf2_snpcs.settings.InfiniteAmmo", "vj_gf2_infinite_ammo")
				--Panel:NumSlider("#vj_gf2_snpcs.settings.BulletDamageMultipler", "vj_gf2_bullet_damage_multipler", 0, 1, 2)
				Panel:CheckBox("#vj_gf2_snpcs.settings.FindCoverOnReload", "vj_gf2_npc_find_cover_on_reload")
				--Panel:CheckBox("#vj_gf2_snpcs.settings.UsePoseParameterMovement", "vj_gf2_npc_use_pose_parameter_movement")
				Panel:Help("#vj_gf2_snpcs.settings.NPC_Shield.Title")
				Panel:CheckBox("#vj_gf2_snpcs.settings.NPC_Shield", "vj_gf2_npc_shield")
				Panel:CheckBox("#vj_gf2_snpcs.settings.NPC_Shield_ExceedMaxHealth", "vj_gf2_npc_shield_exceed_maxhealth")
				Panel:NumSlider("#vj_gf2_snpcs.settings.NPC_ShieldMultipler", "vj_gf2_npc_shield_multipler", 0, 5, 2)
				Panel:NumSlider("#vj_gf2_snpcs.settings.NPC_ShieldRadiusMultipler", "vj_gf2_npc_shield_radius_multipler", 0, 5, 2)
				Panel:CheckBox("#vj_gf2_snpcs.settings.NPC_Shield_RicochetBullets", "vj_gf2_npc_shield_ricochet")
				Panel:NumSlider("#vj_gf2_snpcs.settings.NPC_Shield_RicochetBullets_Chance", "vj_gf2_npc_shield_ricochet_chance", 0, 100, 0)
				Panel:NumSlider("#vj_gf2_snpcs.settings.NPC_Shield_RicochetBullets_DamageScale", "vj_gf2_npc_shield_ricochet_damage_scale", 0, 5, 2)
				Panel:Help("#vj_gf2_snpcs.settings.NPC_Element.Title")
				Panel:CheckBox("#vj_gf2_snpcs.settings.NPC_Element.ElectricEnabled", "vj_gf2_npc_element_electric_enabled")
				Panel:NumSlider("#vj_gf2_snpcs.settings.NPC_Element.ElectricDamageMultipler", "vj_gf2_npc_element_electric_damage_multipler", 0, 5, 2)
				Panel:NumSlider("#vj_gf2_snpcs.settings.NPC_Element.ElectricRadiusMultipler", "vj_gf2_npc_element_electric_radius_multipler", 0, 5, 2)
				Panel:CheckBox("#vj_gf2_snpcs.settings.NPC_Element.FreezingEnabled", "vj_gf2_npc_element_freezing_enabled")
				Panel:NumSlider("#vj_gf2_snpcs.settings.NPC_Element.FreezingRadiusMultipler", "vj_gf2_npc_element_freezing_radius_multipler", 0, 5, 2)
				Panel:CheckBox("#vj_gf2_snpcs.settings.NPC_Element.FireEnabled", "vj_gf2_npc_element_fire_enabled")
				Panel:CheckBox("#vj_gf2_snpcs.settings.NPC_Element.AcidEnabled", "vj_gf2_npc_element_acid_enabled")
				Panel:NumSlider("#vj_gf2_snpcs.settings.NPC_Element.AcidDamageMultipler", "vj_gf2_npc_element_acid_damage_multipler", 0, 1, 2)
				Panel:NumSlider("#vj_gf2_snpcs.settings.NPC_Element.AcidTimeMultipler", "vj_gf2_npc_element_acid_time_multipler", 0, 5, 0)
				Panel:CheckBox("#vj_gf2_snpcs.settings.NPC_Element.WaterEnabled", "vj_gf2_npc_element_water_enabled")
				Panel:NumSlider("#vj_gf2_snpcs.settings.NPC_Element.WaterHP_ReduceRate", "vj_gf2_npc_element_water_hp_reduce_rate", 0, 1, 2)
				Panel:CheckBox("#vj_gf2_snpcs.settings.NPC_SpeedModifier", "vj_gf2_speed_modifier")
				Panel:CheckBox("#vj_gf2_snpcs.settings.NPC_AnimationSpeedModifier", "vj_gf2_animation_speed_modifier")
				Panel:CheckBox("#vj_gf2_snpcs.settings.NPC_Leva_Hacking", "vj_gf2_npc_leva_hacking")
				Panel:CheckBox("#vj_gf2_snpcs.settings.NPC_Charolic_Ignite_Target", "vj_gf2_npc_charolic_ignite_target")
				Panel:CheckBox("#vj_gf2_snpcs.settings.NPC_Golyat_Damage_Friendly", "vj_gf2_npc_golyat_damage_friendly")
				Panel:NumSlider("#vj_gf2_snpcs.settings.NPC_Deichgraf.Missile_Count", "vj_gf2_npc_deichgraf_missile_count", 1, 12, 0)
				local GF2_VOICE_LANGUAGE = Panel:ComboBox("#vj_gf2_snpcs.settings.NPC_VoiceLanguage", "vj_gf2_npc_voice_language")
				--GF2_VOICE_LANGUAGE:AddChoice("English", "en", false, "flags16/us.png")
				GF2_VOICE_LANGUAGE:AddChoice("简体中文", "cn", false, "flags16/cn.png")
				GF2_VOICE_LANGUAGE:AddChoice("日本語", "jp", false, "flags16/jp.png")
			else
				Panel:Help("#vjbase.menu.general.admin.not")
				Panel:ControlHelp("#vjbase.menu.general.admin.only")
			end
			Panel:Help("")
			Panel:Help("#vjbase.menu.settings.client.label")
			Panel:CheckBox("#vj_gf2_snpcs.settings.EnableSubtitles", "vj_gf2_subtitles")
			Panel:CheckBox("#vj_gf2_snpcs.settings.SubtitlesFallback", "vj_gf2_subtitles_fallback")
			Panel:ControlHelp("#vj_gf2_snpcs.settings.SubtitlesFallback.Help")
			local gf2_subtitle_language_combo_box = Panel:ComboBox("#vj_gf2_snpcs.settings.SubtitleLanguage", "vj_gf2_subtitles_language")
			gf2_subtitle_language_combo_box:AddChoice("English", "english", false, "flags16/us.png")
			gf2_subtitle_language_combo_box:AddChoice("简体中文", "schinese", false, "flags16/cn.png")
			gf2_subtitle_language_combo_box:AddChoice("日本語", "japanese", false, "flags16/jp.png")

			Panel:CheckBox("#vj_gf2_snpcs.settings.DrawShield", "vj_gf2_draw_shield")
			Panel:CheckBox("#vj_gf2_snpcs.settings.Attachment_DrawLaser", "vj_gf2_attachment_draw_laser")
			Panel:CheckBox("#vj_gf2_snpcs.settings.DrawBullets", "vj_gf2_draw_bullets")
		end)
	end)

	net.Receive( "GF2_DollInfo", function( len, ply )
		local Entity = net.ReadEntity()
		local DollName = string.format(language.GetPhrase("vj_gf2_snpcs.Name"),Entity.PrintName)
		local DollSquad = string.format(language.GetPhrase("vj_gf2_snpcs.Affiliation"),language.GetPhrase(Entity.SquadName))
		local DollModel = string.format(language.GetPhrase("vj_gf2_snpcs.BodyModel"),Entity.BodyModel)
		local DollWeapon = string.format(language.GetPhrase("vj_gf2_snpcs.ImprintID"),language.GetPhrase(Entity:GetActiveWeapon().PrintName))

		hook.Add( "HUDPaint", "VJ_GF2_Controller_HUD", function()
			if IsValid(Entity) then
				surface.SetFont("DermaLarge")
				local padX = 20
				local padY = 5
				local PosX = 0.1
				local PosY = 0.1
				local Text = DollName.."\n"..DollSquad.."\n"..DollModel.."\n"..DollWeapon
				local tW, tH = surface.GetTextSize( Text )
				surface.SetDrawColor( 0, 0, 0, 100 )
				surface.DrawRect( ScrW() * PosX - (tW+padX * 2)/2, ScrH() * PosY, tW + padX * 2, tH + padY * 2 )
				draw.DrawText(Text, "DermaLarge", ScrW() * PosX, ScrH() * PosY, color_white, 1)
	
				local PosX = 0.9
				local PosY = 0.9
				local Text = Entity:GetActiveWeapon().PrintName.."\n"..Entity:GetActiveWeapon():Clip1().."|"..Entity:GetActiveWeapon():GetMaxClip1()
				local tW, tH = surface.GetTextSize( Text )
				surface.DrawRect( ScrW() * PosX - (tW+padX * 2)/2, ScrH() * PosY, tW + padX * 2, tH + padY * 2 )
				draw.DrawText(Text, "DermaLarge", ScrW() * PosX, ScrH() * PosY, color_white, 1)

				local PosX = 0.1
				local PosY = 0.9
				local Text = "#Valve_Hud_HEALTH".."\n"..Entity:Health().."|"..Entity:GetMaxHealth()
				local tW, tH = surface.GetTextSize( Text )
				surface.DrawRect( ScrW() * PosX - (tW+padX * 2)/2, ScrH() * PosY, tW + padX * 2, tH + padY * 2 )
				draw.DrawText(Text, "DermaLarge", ScrW() * PosX, ScrH() * PosY, color_white, 1)
			end
		end )
	end )

	net.Receive( "GF2_DollInfo_End", function( len, ply )
		hook.Remove("HUDPaint", "VJ_GF2_Controller_HUD")
	end)

	net.Receive( "GF2_DollDestoryed", function( len, ply )
		local Entity = net.ReadEntity()
		chat.AddText(string.format(language.GetPhrase("vj_gf2_snpcs.Destoryed"),Entity.PrintName))
	end)
end
