
VJ.AddPlugin("Girls' Frontline 2: Exilium", "NPC","BETA")

local vCat = "#vj_gf2_snpcs.spawnmenu.Title"
local vCatUnf = "#vj_gf2_snpcs.spawnmenu.Title_Unf"
VJ.AddCategoryInfo(vCat, {Icon = "icons/gf2.png"})

VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Nemesis","npc_vj_gf2_nemesis",{"weapon_vj_gf2_om50"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Nemesis_Tactical","npc_vj_gf2_nemesis_tactical",{"weapon_vj_gf2_om50"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Nemesis_WanderingStarTrial","npc_vj_gf2_nemesis_wandering_star_trial",{"weapon_vj_gf2_om50"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Nemesis_SereneDarkRiver","npc_vj_gf2_nemesis_serene_dark_river",{"weapon_vj_gf2_om50"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Tololo","npc_vj_gf2_tololo",{"weapon_vj_gf2_ak_alfa"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Tololo_TwilightMilkyWay","npc_vj_gf2_tololo_twilight_milky_way",{"weapon_vj_gf2_ak_alfa"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Cheeta","npc_vj_gf2_cheeta",{"weapon_vj_gf2_mp7"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Cheeta_CircuitSparks","npc_vj_gf2_cheeta_circuit_sparks",{"weapon_vj_gf2_mp7"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Groza","npc_vj_gf2_groza",{"weapon_vj_gf2_ots14"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Groza_DawnOfBattle","npc_vj_gf2_groza_dawn_of_battle",{"weapon_vj_gf2_ots14"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Groza_VioletRain","npc_vj_gf2_groza_violet_rain",{"weapon_vj_gf2_ots14"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Groza_Tactical","npc_vj_gf2_groza_tactical",{"weapon_vj_gf2_ots14"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Peritya","npc_vj_gf2_peritya",{"weapon_vj_gf2_pkp_sp"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Peritya_BornHuntress","npc_vj_gf2_peritya_born_huntress",{"weapon_vj_gf2_pkp_sp"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Peritya_OperationPechenyan","npc_vj_gf2_peritya_operation_pechenyan",{"weapon_vj_gf2_pkp_sp"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Qiongjiu","npc_vj_gf2_qiongjiu",{"weapon_vj_gf2_qbz191"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Qiongjiu_BoundlessValor","npc_vj_gf2_qiongjiu_boundless_valor",{"weapon_vj_gf2_qbz191"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Nagant","npc_vj_gf2_nagant",{"weapon_vj_gf2_m1895_revolver"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Nagant_SummerPitcher","npc_vj_gf2_nagant_summer_pitcher",{"weapon_vj_gf2_m1895_revolver"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Suomi","npc_vj_gf2_suomi",{"weapon_vj_gf2_kp31"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Suomi_MidsummerPixie","npc_vj_gf2_suomi_midsummer_pixie",{"weapon_vj_gf2_kp31"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Sabrina","npc_vj_gf2_sabrina",{"weapon_vj_gf2_spas12"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Sabrina_BerryZabaione","npc_vj_gf2_sabrina_berry_zabaione",{"weapon_vj_gf2_spas12"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Mechty","npc_vj_gf2_mechty",{"weapon_vj_gf2_g11"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Vepley","npc_vj_gf2_vepley",{"weapon_vj_gf2_vepr_12"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Vepley_SparklingWish","npc_vj_gf2_vepley_sparkling_wish",{"weapon_vj_gf2_vepr_12"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Vepley_SummerEcho","npc_vj_gf2_vepley_summer_echo",{"weapon_vj_gf2_vepr_12"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Colphne","npc_vj_gf2_colphne",{"weapon_vj_gf2_taurus_curve"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Colphne_Tactical","npc_vj_gf2_colphne_tactical",{"weapon_vj_gf2_taurus_curve"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Colphne_SilentVoice","npc_vj_gf2_colphne_silent_voice",{"weapon_vj_gf2_taurus_curve"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Vector","npc_vj_gf2_vector",{"weapon_vj_gf2_kriss_vector"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Vector_ViviSometimesHidesHerMolotov","npc_vj_gf2_vector_vivi_sometimes_hides_her_molotov",{"weapon_vj_gf2_kriss_vector"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Vector_MolotovBunny","npc_vj_gf2_vector_molotov_bunny",{"weapon_vj_gf2_kriss_vector"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Lenna","npc_vj_gf2_lenna",{"weapon_vj_gf2_ump9"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Lenna_EnergeticMagic","npc_vj_gf2_lenna_energetic_magic",{"weapon_vj_gf2_ump9"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Lenna_FlyingPhantom","npc_vj_gf2_lenna_flying_phantom",{"weapon_vj_gf2_ump9"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Leva","npc_vj_gf2_leva",{"weapon_vj_gf2_ump45"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Leva_DiamondFlower","npc_vj_gf2_leva_diamond_flower",{"weapon_vj_gf2_ump45"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Jiangyu","npc_vj_gf2_jiangyu",{"weapon_vj_gf2_qbz97"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Klukai","npc_vj_gf2_klukai",{"weapon_vj_gf2_hk416"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Klukai_AstralLuminous","npc_vj_gf2_klukai_astral_luminous",{"weapon_vj_gf2_hk416"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Klukai_SpeedStar","npc_vj_gf2_klukai_speed_star",{"weapon_vj_gf2_hk416"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Zhaohui","npc_vj_gf2_zhaohui",{"weapon_vj_gf2_csls06"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Zhaohui_RapidGrid","npc_vj_gf2_zhaohui_rapid_grid",{"weapon_vj_gf2_csls06"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Daiyan","npc_vj_gf2_daiyan",{"weapon_vj_gf2_qbz95"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Daiyan_ExquisiteJade","npc_vj_gf2_daiyan_exquisite_jade",{"weapon_vj_gf2_qbz95"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Ksenia","npc_vj_gf2_ksenia",{"weapon_vj_gf2_aps"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Faye","npc_vj_gf2_faye",{"weapon_vj_gf2_cz75"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Faye_FlurryCrimson","npc_vj_gf2_faye_flurry_crimson",{"weapon_vj_gf2_cz75"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Sharkry","npc_vj_gf2_sharkry",{"weapon_vj_gf2_xcr"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Sharkry_SwimsuitIdol","npc_vj_gf2_sharkry_swimsuit_idol",{"weapon_vj_gf2_xcr"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Centaureissi","npc_vj_gf2_centaureissi",{"weapon_vj_gf2_g36"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Dushevnaya","npc_vj_gf2_dushevnaya",{"weapon_vj_gf2_ksvk"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Robella","npc_vj_gf2_robella",{"weapon_vj_gf2_ro635"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Robella_FutureNavigator","npc_vj_gf2_robella_future_navigator",{"weapon_vj_gf2_ro635"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Charolic","npc_vj_gf2_charolic",{"weapon_vj_gf2_blade"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Charolic_LeapingRabbit","npc_vj_gf2_charolic_leaping_rabbit",{"weapon_vj_gf2_blade"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Charolic_Tactical","npc_vj_gf2_charolic_tactical",{"weapon_vj_gf2_blade"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Papasha","npc_vj_gf2_papasha",{"weapon_vj_gf2_ppsh41"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Florence","npc_vj_gf2_florence",{"weapon_vj_gf2_pa15"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Florence_MarvelousYamPastry","npc_vj_gf2_florence_marvelous_yam_pastry",{"weapon_vj_gf2_pa15"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Unknown_Groza","npc_vj_gf2_unknown_groza",{"weapon_vj_gf2_ots14"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Varjager_Soldier","npc_vj_gf2_varjager_soldier",{"weapon_vj_gf2_varjager_ak101","weapon_vj_gf2_varjager_ak74"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Varjager_Medic","npc_vj_gf2_varjager_medic",{"weapon_vj_glock17"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Varjager_Warrior","npc_vj_gf2_varjager_warrior",{"weapon_vj_gf2_varjager_axe","weapon_vj_gf2_varjager_mpl40","weapon_vj_gf2_varjager_taiga"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Varjager_Sniper","npc_vj_gf2_varjager_sniper",{"weapon_vj_gf2_varjager_mosin"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Varjager_Heavy","npc_vj_gf2_varjager_heavy",{"weapon_vj_rpg","weapon_vj_spas12"},vCat)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Sextans","npc_vj_gf2_sextans",{"weapon_vj_gf2_sextans_revolver","weapon_vj_gf2_sextans_flintlock"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Lose_Sextans","npc_vj_gf2_lose_sextans",{"weapon_vj_gf2_lose_sextans_cannon"},vCatUnf)
VJ.AddNPC_HUMAN("#vj_gf2_snpcs.Andoris","npc_vj_gf2_andoris",{"weapon_vj_gf2_g36k"},vCatUnf)

VJ.AddNPC("#vj_gf2_snpcs.Golyat","npc_vj_gf2_golyat_base",vCat)
VJ.AddNPC("#vj_gf2_snpcs.Golyat_Electric","npc_vj_gf2_golyat_electric",vCatUnf)
VJ.AddNPC("#vj_gf2_snpcs.Golyat_Red","npc_vj_gf2_golyat_red",vCat)
VJ.AddNPC("#vj_gf2_snpcs.Golyat_Football","npc_vj_gf2_golyat_football",vCat)
VJ.AddNPC("#vj_gf2_snpcs.Golyat_Fire","npc_vj_gf2_golyat_fire",vCatUnf)
VJ.AddNPC("#vj_gf2_snpcs.Golyat_Ice","npc_vj_gf2_golyat_ice",vCatUnf)
VJ.AddNPC("#vj_gf2_snpcs.Golyat_Tank","npc_vj_gf2_golyat_tank",vCatUnf)
VJ.AddNPC("#vj_gf2_snpcs.Blusphere", "npc_vj_gf2_blusphere",vCatUnf)
VJ.AddNPC("#vj_gf2_snpcs.Andoris_Turret", "npc_vj_gf2_andoris_turret",vCatUnf)

-- Weapons
VJ.AddNPCWeapon("OM 50", "weapon_vj_gf2_om50", vCat)
VJ.AddNPCWeapon("AK Alfa", "weapon_vj_gf2_ak_alfa", vCat)
VJ.AddNPCWeapon("MP7", "weapon_vj_gf2_mp7", vCat)
VJ.AddNPCWeapon("OTs-14", "weapon_vj_gf2_ots14", vCat)
VJ.AddNPCWeapon("M1895 Revolver", "weapon_vj_gf2_m1895_revolver", vCat)
VJ.AddNPCWeapon("PKP-SP", "weapon_vj_gf2_pkp_sp", vCat)
VJ.AddNPCWeapon("QBZ-191", "weapon_vj_gf2_qbz191", vCat)
VJ.AddNPCWeapon("SPAS-12", "weapon_vj_gf2_spas12", vCat)
VJ.AddNPCWeapon("VEPR-12", "weapon_vj_gf2_vepr_12", vCat)
VJ.AddNPCWeapon("G11", "weapon_vj_gf2_g11", vCat)
VJ.AddNPCWeapon("Taurus Curve", "weapon_vj_gf2_taurus_curve", vCat)
VJ.AddNPCWeapon("KRISS Vector", "weapon_vj_gf2_kriss_vector", vCat)
VJ.AddNPCWeapon("UMP9", "weapon_vj_gf2_ump9", vCat)
VJ.AddNPCWeapon("UMP45", "weapon_vj_gf2_ump45", vCat)
VJ.AddNPCWeapon("KP/-31", "weapon_vj_gf2_kp31", vCat)
VJ.AddNPCWeapon("QBZ-97", "weapon_vj_gf2_qbz97", vCat)
VJ.AddNPCWeapon("HK416", "weapon_vj_gf2_hk416", vCat)
VJ.AddNPCWeapon("CS/LS06", "weapon_vj_gf2_csls06", vCat)
VJ.AddNPCWeapon("QBZ-95", "weapon_vj_gf2_qbz95", vCat)
VJ.AddNPCWeapon("APS", "weapon_vj_gf2_aps", vCat)
VJ.AddNPCWeapon("CZ 75", "weapon_vj_gf2_cz75", vCat)
VJ.AddNPCWeapon("WA2000", "weapon_vj_gf2_wa2000", vCat)
VJ.AddNPCWeapon("XCR", "weapon_vj_gf2_xcr", vCat)
VJ.AddNPCWeapon("K2", "weapon_vj_gf2_k2", vCat)
VJ.AddNPCWeapon("VSK-94", "weapon_vj_gf2_vsk94", vCat)
VJ.AddNPCWeapon("RO635", "weapon_vj_gf2_ro635", vCat)
VJ.AddNPCWeapon("PPSH-41", "weapon_vj_gf2_ppsh41", vCat)
VJ.AddNPCWeapon("MP5", "weapon_vj_gf2_mp5", vCat)
VJ.AddNPCWeapon("M1903", "weapon_vj_gf2_m1903", vCat)
VJ.AddNPCWeapon("M1891", "weapon_vj_gf2_m1891", vCat)
VJ.AddNPCWeapon("M1 Super 90", "weapon_vj_gf2_m1_super90", vCat)
VJ.AddNPCWeapon("KSVK", "weapon_vj_gf2_ksvk", vCat)
VJ.AddNPCWeapon("Hawk Type 97", "weapon_vj_gf2_hawk_type97", vCat)
VJ.AddNPCWeapon("Galil ARM", "weapon_vj_gf2_galil_arm", vCat)
VJ.AddNPCWeapon("G36K", "weapon_vj_gf2_g36k", vCat)
VJ.AddNPCWeapon("G36", "weapon_vj_gf2_g36", vCat)
VJ.AddNPCWeapon("PA-15", "weapon_vj_gf2_pa15", vCat)
VJ.AddNPCWeapon("AA-12", "weapon_vj_gf2_aa12", vCat)
VJ.AddNPCWeapon("Plasma Cannon", "weapon_vj_gf2_lose_sextans_cannon", vCat)

VJ.AddNPCWeapon("AK-101", "weapon_vj_gf2_varjager_ak101", vCat)
VJ.AddNPCWeapon("AK-74", "weapon_vj_gf2_varjager_ak74", vCat)
VJ.AddNPCWeapon("Mosin", "weapon_vj_gf2_varjager_mosin", vCat)
VJ.AddNPCWeapon("Axe", "weapon_vj_gf2_varjager_axe", vCat)
VJ.AddNPCWeapon("MPL40", "weapon_vj_gf2_varjager_mpl40", vCat)
VJ.AddNPCWeapon("Taiga", "weapon_vj_gf2_varjager_taiga", vCat)

VJ.AddNPCWeapon("Klukai's Axe", "weapon_vj_gf2_klukai_axe", vCat)
VJ.AddNPCWeapon("Blade", "weapon_vj_gf2_blade", vCat)

VJ.AddEntity("#vj_gf2_items.Colphne_Healthkit", "sent_gf2_colphne_healthkit", "IBRS", false, 0, true, vCat)
VJ.AddEntity("#vj_gf2_items.Colphne_Syringe", "sent_gf2_colphne_syringe", "IBRS", false, 0, true, vCat)
VJ.AddEntity("#vj_gf2_items.Colphne_Bandage", "sent_gf2_colphne_bandage", "IBRS", false, 0, true, vCat)
if (file.Exists( "entities/sent_gf2_musicbox.lua", "LUA" )) then
VJ.AddEntity("#vj_gf2_ents.Music_Box", "sent_gf2_musicbox", "IBRS", false, 0, true, vCat)
end

-- Precache Models --
-- NPC Models
util.PrecacheModel("models/gf2/nemesis_combat.mdl")
util.PrecacheModel("models/gf2/nemesis_wandering_star_trial.mdl")
util.PrecacheModel("models/gf2/nemesis_serene_dark_river.mdl")
util.PrecacheModel("models/gf2/nemesis_tactical.mdl")
util.PrecacheModel("models/gf2/tololo_combat.mdl")
util.PrecacheModel("models/gf2/tololo_twilight_milky_way.mdl")
util.PrecacheModel("models/gf2/cheeta_combat.mdl")
util.PrecacheModel("models/gf2/cheeta_circuit_sparks.mdl")
util.PrecacheModel("models/gf2/groza_combat.mdl")
util.PrecacheModel("models/gf2/groza_dawn_of_battle.mdl")
util.PrecacheModel("models/gf2/groza_violet_rain.mdl")
util.PrecacheModel("models/gf2/groza_tactical.mdl")
util.PrecacheModel("models/gf2/peritya_combat.mdl")
util.PrecacheModel("models/gf2/peritya_born_huntress.mdl")
util.PrecacheModel("models/gf2/peritya_operation_pechenyan.mdl")
util.PrecacheModel("models/gf2/qiongjiu_combat.mdl")
util.PrecacheModel("models/gf2/qiongjiu_boundless_valor.mdl")
util.PrecacheModel("models/gf2/sabrina_combat.mdl")
util.PrecacheModel("models/gf2/sabrina_berry_zabaione.mdl")
util.PrecacheModel("models/gf2/mechty_combat.mdl")
util.PrecacheModel("models/gf2/nagant_combat.mdl")
util.PrecacheModel("models/gf2/nagant_summer_pitcher.mdl")
util.PrecacheModel("models/gf2/vepley_combat.mdl")
util.PrecacheModel("models/gf2/vepley_sparkling_wish.mdl")
util.PrecacheModel("models/gf2/vepley_summer_echo.mdl")
util.PrecacheModel("models/gf2/colphne_combat.mdl")
util.PrecacheModel("models/gf2/colphne_tactical.mdl")
util.PrecacheModel("models/gf2/vector_combat.mdl")
util.PrecacheModel("models/gf2/vector_molotov_bunny.mdl")
util.PrecacheModel("models/gf2/lenna_combat.mdl")
util.PrecacheModel("models/gf2/lenna_energetic_magic.mdl")
util.PrecacheModel("models/gf2/lenna_flying_phantom.mdl")
util.PrecacheModel("models/gf2/leva_combat.mdl")
util.PrecacheModel("models/gf2/leva_diamond_flower.mdl")
util.PrecacheModel("models/gf2/suomi_combat.mdl")
util.PrecacheModel("models/gf2/suomi_midsummer_pixie.mdl")
util.PrecacheModel("models/gf2/jiangyu_combat.mdl")
util.PrecacheModel("models/gf2/zhaohui_combat.mdl")
util.PrecacheModel("models/gf2/zhaohui_rapid_grid.mdl")
util.PrecacheModel("models/gf2/daiyan_combat.mdl")
util.PrecacheModel("models/gf2/daiyan_exquisite_jade.mdl")
util.PrecacheModel("models/gf2/ksenia_combat.mdl")
util.PrecacheModel("models/gf2/faye_combat.mdl")
util.PrecacheModel("models/gf2/faye_flurry_crimson.mdl")
util.PrecacheModel("models/gf2/sharkry_combat.mdl")
util.PrecacheModel("models/gf2/sharkry_swimsuit_idol.mdl")
util.PrecacheModel("models/gf2/centaureissi_combat.mdl")
util.PrecacheModel("models/gf2/dushevnaya_combat.mdl")
util.PrecacheModel("models/gf2/robella_combat.mdl")
util.PrecacheModel("models/gf2/robella_future_navigator.mdl")
util.PrecacheModel("models/gf2/charolic_combat.mdl")
util.PrecacheModel("models/gf2/charolic_leaping_rabbit.mdl")
util.PrecacheModel("models/gf2/charolic_tactical.mdl")
util.PrecacheModel("models/gf2/florence_combat.mdl")
util.PrecacheModel("models/gf2/florence_marvelous_yam_pastry.mdl")
util.PrecacheModel("models/bandits/varyag.mdl")
util.PrecacheModel("models/gf2/golyat.mdl")
util.PrecacheModel("models/gf2/blusphere.mdl")
util.PrecacheModel("models/gf2/sextans_combat.mdl")
util.PrecacheModel("models/gf2/lose_sextans_combat.mdl")

-- Weapon Models
util.PrecacheModel("models/weapons/w_nemesis_om50.mdl")
util.PrecacheModel("models/weapons/w_tololo_ak_alfa.mdl")
util.PrecacheModel("models/weapons/w_cheeta_mp7.mdl")
util.PrecacheModel("models/weapons/w_groza_ots14.mdl")
util.PrecacheModel("models/weapons/w_peritya_pkp_sp.mdl")
util.PrecacheModel("models/weapons/w_qiongjiu_qbz_191.mdl")
util.PrecacheModel("models/weapons/w_sabrina_spas12.mdl")
util.PrecacheModel("models/weapons/w_mechty_g11.mdl")
util.PrecacheModel("models/weapons/w_nagant_m1895_revolver.mdl")
util.PrecacheModel("models/weapons/w_vepley_vepr12_sr.mdl")
util.PrecacheModel("models/weapons/w_colphne_taurus_curve.mdl")
util.PrecacheModel("models/weapons/w_vector_kriss_vector.mdl")
util.PrecacheModel("models/weapons/w_lenna_hk_ump9.mdl")
util.PrecacheModel("models/weapons/w_leva_hk_ump45.mdl")
util.PrecacheModel("models/weapons/w_suomi_kp31.mdl")
util.PrecacheModel("models/weapons/w_jiangyu_qbz_97.mdl")
util.PrecacheModel("models/weapons/w_klukai_hk416.mdl")
util.PrecacheModel("models/weapons/w_zhaohui_csls06.mdl")
util.PrecacheModel("models/weapons/w_daiyan_qbz_95.mdl")
util.PrecacheModel("models/weapons/w_faye_cz75.mdl")
util.PrecacheModel("models/weapons/w_ksenia_aps.mdl")
util.PrecacheModel("models/weapons/w_sharkry_xcr.mdl")
util.PrecacheModel("models/weapons/w_centaureissi_g36.mdl")
util.PrecacheModel("models/weapons/w_dusevnyj_ksvk.mdl")
util.PrecacheModel("models/weapons/w_florence_pa-15.mdl")
util.PrecacheModel("models/weapons/w_lose_sextans_cannon.mdl")

-- Grenade Models
util.PrecacheModel("models/prop/gfl2_cheeta_lollipop_grenade.mdl")
util.PrecacheModel("models/prop/gfl2_peritya_grenade.mdl")
util.PrecacheModel("models/prop/gfl2_vector_incendiary_grenade.mdl")

-- Misc Models
util.PrecacheModel("models/prop/gfl2_cheeta_lollipop_1.mdl")
util.PrecacheModel("models/prop/gfl2_cheeta_lollipop_2.mdl")
util.PrecacheModel("models/prop/gfl2_cheeta_lollipop_3.mdl")
util.PrecacheModel("models/prop/gfl2_colphne_bandage.mdl")
util.PrecacheModel("models/prop/gfl2_colphne_medkit.mdl")
util.PrecacheModel("models/prop/gfl2_colphne_syringe.mdl")
util.PrecacheModel("models/prop/gfl2_mechty_energy_drink.mdl")
util.PrecacheModel("models/bandits/varyag_shield.mdl")

-- ConVars --
VJ.AddConVar("vj_gf2_varjager_h",250)
VJ.AddConVar("vj_gf2_varjager_d",25)

VJ.AddConVar("vj_gf2_nemesis_h",200)
VJ.AddConVar("vj_gf2_nemesis_d",40)
VJ.AddConVar("vj_gf2_tololo_h",300)
VJ.AddConVar("vj_gf2_tololo_d",60)
VJ.AddConVar("vj_gf2_cheeta_h",250)
VJ.AddConVar("vj_gf2_cheeta_d",50)
VJ.AddConVar("vj_gf2_groza_h",300)
VJ.AddConVar("vj_gf2_groza_d",70)
VJ.AddConVar("vj_gf2_peritya_h",500)
VJ.AddConVar("vj_gf2_peritya_d",25)
VJ.AddConVar("vj_gf2_qiongjiu_h",300)
VJ.AddConVar("vj_gf2_qiongjiu_d",60)
VJ.AddConVar("vj_gf2_nagant_h",250)
VJ.AddConVar("vj_gf2_nagant_d",25)
VJ.AddConVar("vj_gf2_suomi_h",400)
VJ.AddConVar("vj_gf2_suomi_d",20)
VJ.AddConVar("vj_gf2_sabrina_h",350)
VJ.AddConVar("vj_gf2_sabrina_d",40)
VJ.AddConVar("vj_gf2_mechty_h",450)
VJ.AddConVar("vj_gf2_mechty_d",20)
VJ.AddConVar("vj_gf2_vepley_h",300)
VJ.AddConVar("vj_gf2_vepley_d",75)
VJ.AddConVar("vj_gf2_colphne_h",200)
VJ.AddConVar("vj_gf2_colphne_d",15)
VJ.AddConVar("vj_gf2_vector_h",300)
VJ.AddConVar("vj_gf2_vector_d",60)
VJ.AddConVar("vj_gf2_lenna_h",300)
VJ.AddConVar("vj_gf2_lenna_d",60)
VJ.AddConVar("vj_gf2_leva_h",350)
VJ.AddConVar("vj_gf2_leva_d",80)
VJ.AddConVar("vj_gf2_jiangyu_h",250)
VJ.AddConVar("vj_gf2_jiangyu_d",50)
VJ.AddConVar("vj_gf2_klukai_h",300)
VJ.AddConVar("vj_gf2_klukai_d",60)
VJ.AddConVar("vj_gf2_zhaohui_h",350)
VJ.AddConVar("vj_gf2_zhaohui_d",40)
VJ.AddConVar("vj_gf2_daiyan_h",300)
VJ.AddConVar("vj_gf2_daiyan_d",80)
VJ.AddConVar("vj_gf2_ksenia_h",250)
VJ.AddConVar("vj_gf2_ksenia_d",25)
VJ.AddConVar("vj_gf2_faye_h",275)
VJ.AddConVar("vj_gf2_faye_d",30)
VJ.AddConVar("vj_gf2_sharkry_h",225)
VJ.AddConVar("vj_gf2_sharkry_d",25)
VJ.AddConVar("vj_gf2_centaureissi_h",300)
VJ.AddConVar("vj_gf2_centaureissi_d",30)
VJ.AddConVar("vj_gf2_unknown_groza_h",1000)
VJ.AddConVar("vj_gf2_unknown_groza_d",200)
VJ.AddConVar("vj_gf2_unknown_groza_dummy_h",250)
VJ.AddConVar("vj_gf2_unknown_groza_dummy_d",50)
VJ.AddConVar("vj_gf2_dushevnaya_h",225)
VJ.AddConVar("vj_gf2_dushevnaya_d",45)
VJ.AddConVar("vj_gf2_robella_h",275)
VJ.AddConVar("vj_gf2_robella_d",25)
VJ.AddConVar("vj_gf2_charolic_h",350)
VJ.AddConVar("vj_gf2_charolic_d",75)
VJ.AddConVar("vj_gf2_florence_h",225)
VJ.AddConVar("vj_gf2_florence_d",15)
VJ.AddConVar("vj_gf2_sextans_h",1500)
VJ.AddConVar("vj_gf2_sextans_d",100)
VJ.AddConVar("vj_gf2_lose_sextans_h",3000)
VJ.AddConVar("vj_gf2_lose_sextans_d",200)
VJ.AddConVar("vj_gf2_andoris_h",250)
VJ.AddConVar("vj_gf2_andoris_d",25)

VJ.AddConVar("vj_gf2_om50_d",150)
VJ.AddConVar("vj_gf2_ak_alfa_d",40)
VJ.AddConVar("vj_gf2_mp7_d",25)
VJ.AddConVar("vj_gf2_ots14_d",60)
VJ.AddConVar("vj_gf2_pkp_sp_d",75)
VJ.AddConVar("vj_gf2_qbz191_d",50)
VJ.AddConVar("vj_gf2_m1895_revolver_d",75)
VJ.AddConVar("vj_gf2_spas12_d",40)
VJ.AddConVar("vj_gf2_g11_d",25)
VJ.AddConVar("vj_gf2_vepr_12_d",25)
VJ.AddConVar("vj_gf2_taurus_curve_d",15)
VJ.AddConVar("vj_gf2_kriss_vector_d",30)
VJ.AddConVar("vj_gf2_ump9_d",30)
VJ.AddConVar("vj_gf2_ump45_d",35)
VJ.AddConVar("vj_gf2_kp31_d",25)
VJ.AddConVar("vj_gf2_qbz97_d",40)
VJ.AddConVar("vj_gf2_hk416_d",45)
VJ.AddConVar("vj_gf2_csls06_d",30)
VJ.AddConVar("vj_gf2_qbz95_d",55)
VJ.AddConVar("vj_gf2_aps_d",15)
VJ.AddConVar("vj_gf2_cz75_d",20)
VJ.AddConVar("vj_gf2_wa2000_d",125)
VJ.AddConVar("vj_gf2_xcr_d",40)
VJ.AddConVar("vj_gf2_g36_d",30)
VJ.AddConVar("vj_gf2_ksvk_d",250)
VJ.AddConVar("vj_gf2_pa15_d",15)
VJ.AddConVar("vj_gf2_lose_sextans_cannon_d",250)

-- Menu --
local AddConvars = {}
AddConvars["vj_gf2_drop_magazings"] = 1 -- Drop Magazines?
AddConvars["vj_gf2_magazingremovetime"] = 15 -- Magazine Remove time.
AddConvars["vj_gf2_death_expressions"] = 1 -- Death Expressions?
AddConvars["vj_gf2_death_fingerpose"] = 1 -- Death Finger Pose?
AddConvars["vj_gf2_npc_random_bodygroups"] = 1 -- Random Bodygroup for SNPCs?
AddConvars["vj_gf2_npc_shield_multipler"] = 1 -- Shield multipler.
AddConvars["vj_gf2_npc_shield_radius_multipler"] = 1 -- Shield radius multipler.
AddConvars["vj_gf2_npc_shield"] = 1 -- Enable Shield.
AddConvars["vj_gf2_npc_shield_exceed_maxhealth"] = 0 -- Shield can exceed max health.
AddConvars["vj_gf2_npc_element_electric_enabled"] = 1 -- Enable Electric Effects.
AddConvars["vj_gf2_npc_element_electric_damage_multipler"] = 1 -- Electric damage multipler.
AddConvars["vj_gf2_npc_element_electric_radius_multipler"] = 1 -- Electric radius multipler.
AddConvars["vj_gf2_npc_element_freezing_enabled"] = 1 -- Enable Freezing Effects.
AddConvars["vj_gf2_npc_element_freezing_radius_multipler"] = 1 -- Freezing radius multipler.
AddConvars["vj_gf2_npc_element_fire_enabled"] = 1 -- Enable Fire Effects.
AddConvars["vj_gf2_npc_element_acid_enabled"] = 1 -- Enable Acid Effects.
AddConvars["vj_gf2_npc_element_acid_time_multipler"] = 1 -- Acid time multipler.
AddConvars["vj_gf2_npc_element_acid_damage_multipler"] = 0.1 -- Acid damage multipler.
AddConvars["vj_gf2_npc_element_water_enabled"] = 1 -- Enable Water Effects.
AddConvars["vj_gf2_npc_element_water_hp_reduce_rate"] = 0.01 -- Enable Water Effects.
AddConvars["vj_gf2_infinite_ammo"] = 0 -- Infinite Ammo.
AddConvars["vj_gf2_speed_modifier"] = 1 -- Speed Modifier.
AddConvars["vj_gf2_animation_speed_modifier"] = 1 -- Animation Modifier.
AddConvars["vj_gf2_npc_find_cover_on_reload"] = 1 -- Find Cover On Reload.
AddConvars["vj_gf2_npc_charolic_ignite_target"] = 1 -- Charolic Ignite Targets.
AddConvars["vj_gf2_npc_leva_hacking"] = 1 -- Leva Hacking.
AddConvars["vj_gf2_npc_unknown_groza_camo"] = 1 -- Unknown Doll have camo.
AddConvars["vj_gf2_npc_unknown_groza_hack_dolls"] = 1 -- Unknown Doll hack dolls.
AddConvars["vj_gf2_npc_unknown_groza_switch_weapons"] = 1 -- Unknown Doll switch weapons.
AddConvars["vj_gf2_npc_unknown_groza_summon_dummy"] = 1 -- Unknown Doll summon dummies.
AddConvars["vj_gf2_npc_golyat_damage_friendly"] = 1 -- Golyat deals damage to all NPCs.

for k, v in pairs(AddConvars) do
	if !ConVarExists( k ) then CreateConVar( k, v, {FCVAR_ARCHIVE} ) end
end

VJ.AddClientConVar("vj_gf2_draw_shield", 1, "Draw Shield.")
VJ.AddClientConVar("vj_gf2_attachment_draw_laser", 1, "Draw Laser.")
VJ.AddClientConVar("vj_gf2_draw_bullets", 1, "Draw Bullets.")

if CLIENT then
	hook.Add( "PopulateToolMenu", "VJ_ADDTOMENU_GF2", function()
		spawnmenu.AddToolMenuOption( "DrVrej", "SNPC Configures", "Girls' Frontline 2: Exilium", "#vj_gf2_snpcs.settings.Title", "", "", function(Panel) 
			if game.SinglePlayer() or LocalPlayer():IsAdmin() then
				Panel:Help("#vjbase.menu.general.admin.only")
				Panel:CheckBox("#vj_gf2_snpcs.settings.DropMagazines", "vj_gf2_drop_magazings")
				Panel:ControlHelp("#vj_gf2_snpcs.settings.DropMagazines.Desc")
				Panel:NumSlider("#vj_gf2_snpcs.settings.MagazineRemoveTimer", "vj_gf2_magazingremovetime", 5, 60, 0)
				Panel:ControlHelp("#vj_gf2_snpcs.settings.MagazineRemoveTimer.Desc")
				Panel:CheckBox("#vj_gf2_snpcs.settings.DeathExpressions", "vj_gf2_death_expressions")
				Panel:CheckBox("#vj_gf2_snpcs.settings.DeathFingerPose", "vj_gf2_death_fingerpose")
				Panel:CheckBox("#vj_gf2_snpcs.settings.NPC_RandomBodygroups", "vj_gf2_npc_random_bodygroups")
				Panel:CheckBox("#vj_gf2_snpcs.settings.InfiniteAmmo", "vj_gf2_infinite_ammo")
				Panel:CheckBox("#vj_gf2_snpcs.settings.FindCoverOnReload", "vj_gf2_npc_find_cover_on_reload")
				Panel:Help("#vj_gf2_snpcs.settings.NPC_Shield.Title")
				Panel:CheckBox("#vj_gf2_snpcs.settings.NPC_Shield", "vj_gf2_npc_shield")
				Panel:CheckBox("#vj_gf2_snpcs.settings.NPC_Shield_ExceedMaxHealth", "vj_gf2_npc_shield_exceed_maxhealth")
				Panel:NumSlider("#vj_gf2_snpcs.settings.NPC_ShieldMultipler", "vj_gf2_npc_shield_multipler", 0, 5, 2)
				Panel:NumSlider("#vj_gf2_snpcs.settings.NPC_ShieldRadiusMultipler", "vj_gf2_npc_shield_radius_multipler", 0, 5, 2)
				Panel:Help("#vj_gf2_snpcs.settings.NPC_Element.Title")
				Panel:CheckBox("#vj_gf2_snpcs.settings.NPC_Element.ElectricEnabled", "vj_gf2_npc_element_electric_enabled")
				Panel:NumSlider("#vj_gf2_snpcs.settings.NPC_Element.ElectricDamageMultipler", "vj_gf2_npc_element_electric_damage_multipler", 0, 5, 2)
				Panel:NumSlider("#vj_gf2_snpcs.settings.NPC_Element.ElectricRadiusMultipler", "vj_gf2_npc_element_electric_radius_multipler", 0, 5, 2)
				Panel:CheckBox("#vj_gf2_snpcs.settings.NPC_Element.FreezingEnabled", "vj_gf2_npc_element_freezing_enabled")
				Panel:NumSlider("#vj_gf2_snpcs.settings.NPC_Element.FreezingRadiusMultipler", "vj_gf2_npc_element_freezing_radius_multipler", 0, 5, 2)
				Panel:CheckBox("#vj_gf2_snpcs.settings.NPC_Element.FireEnabled", "vj_gf2_npc_element_fire_enabled")
				Panel:CheckBox("#vj_gf2_snpcs.settings.NPC_Element.AcidEnabled", "vj_gf2_npc_element_acid_enabled")
				Panel:NumSlider("#vj_gf2_snpcs.settings.NPC_Element.AcidDamageMultipler", "vj_gf2_npc_element_acid_damage_multipler", 0, 1, 2)
				Panel:NumSlider("#vj_gf2_snpcs.settings.NPC_Element.AcidTimeMultipler", "vj_gf2_npc_element_acid_time_multipler", 0, 5, 0)
				Panel:CheckBox("#vj_gf2_snpcs.settings.NPC_Element.WaterEnabled", "vj_gf2_npc_element_water_enabled")
				Panel:NumSlider("#vj_gf2_snpcs.settings.NPC_Element.WaterHP_ReduceRate", "vj_gf2_npc_element_water_hp_reduce_rate", 0, 1, 2)
				Panel:CheckBox("#vj_gf2_snpcs.settings.NPC_SpeedModifier", "vj_gf2_speed_modifier")
				Panel:CheckBox("#vj_gf2_snpcs.settings.NPC_AnimationSpeedModifier", "vj_gf2_animation_speed_modifier")
				Panel:CheckBox("#vj_gf2_snpcs.settings.NPC_Leva_Hacking", "vj_gf2_npc_leva_hacking")
				Panel:CheckBox("#vj_gf2_snpcs.settings.NPC_Charolic_Ignite_Target", "vj_gf2_npc_charolic_ignite_target")
				Panel:CheckBox("#vj_gf2_snpcs.settings.NPC_Unknown_Groza_Camo", "vj_gf2_npc_unknown_groza_camo")
				Panel:CheckBox("#vj_gf2_snpcs.settings.NPC_Unknown_Groza_Hacking", "vj_gf2_npc_unknown_groza_hack_dolls")
				Panel:CheckBox("#vj_gf2_snpcs.settings.NPC_Unknown_Groza_Switching_Weapons", "vj_gf2_npc_unknown_groza_switch_weapons")
				Panel:CheckBox("#vj_gf2_snpcs.settings.NPC_Unknown_Groza_Summon_Dummy", "vj_gf2_npc_unknown_groza_summon_dummy")
				Panel:CheckBox("#vj_gf2_snpcs.settings.NPC_Golyat_Damage_Friendly", "vj_gf2_npc_golyat_damage_friendly")
			else
				Panel:Help("#vjbase.menu.general.admin.not")
				Panel:ControlHelp("#vjbase.menu.general.admin.only")
			end
			Panel:Help("")
			Panel:Help("#vjbase.menu.settings.client.label")
			Panel:CheckBox("#vj_gf2_snpcs.settings.EnableSubtitles", "vj_gf2_subtitles")
			local gf2_subtitle_language_combo_box = Panel:ComboBox("#vj_gf2_snpcs.settings.SubtitleLanguage", "vj_gf2_subtitles_language")
			gf2_subtitle_language_combo_box:AddChoice("English", "english", false, "flags16/us.png")
			gf2_subtitle_language_combo_box:AddChoice("简体中文", "schinese", false, "flags16/cn.png")
			gf2_subtitle_language_combo_box:AddChoice("日本語", "japanese", false, "flags16/jp.png")

			Panel:CheckBox("#vj_gf2_snpcs.settings.DrawShield", "vj_gf2_draw_shield")
			Panel:CheckBox("#vj_gf2_snpcs.settings.Attachment_DrawLaser", "vj_gf2_attachment_draw_laser")
			Panel:CheckBox("#vj_gf2_snpcs.settings.DrawBullets", "vj_gf2_draw_bullets")
		end)
	end)

	net.Receive( "GF2_DollInfo", function( len, ply )
		local Entity = net.ReadEntity()
		local DollName = string.format(language.GetPhrase("vj_gf2_snpcs.Name"),Entity.PrintName)
		local DollSquad = string.format(language.GetPhrase("vj_gf2_snpcs.Affiliation"),language.GetPhrase(Entity.SquadName))
		local DollModel = string.format(language.GetPhrase("vj_gf2_snpcs.BodyModel"),Entity.BodyModel)
		local DollWeapon = string.format(language.GetPhrase("vj_gf2_snpcs.ImprintID"),Entity:GetActiveWeapon().PrintName)

		hook.Add( "HUDPaint", "VJ_GF2_Controller_HUD", function()
			surface.SetFont("DermaLarge")
			local tW, tH = surface.GetTextSize( DollName.."\n"..DollSquad.."\n"..DollModel.."\n"..DollWeapon )
			local padX = 20
			local padY = 5
			surface.SetDrawColor( 0, 0, 0, 100 )
			surface.DrawRect( 16, 32, tW + padX * 2, tH + padY * 2 )
			draw.DrawText(DollName.."\n"..DollSquad.."\n"..DollModel.."\n"..DollWeapon, "DermaLarge", 32, 32)
		end )
	end )

	net.Receive( "GF2_DollInfo_End", function( len, ply )
		hook.Remove("HUDPaint", "VJ_GF2_Controller_HUD")
	end)

	net.Receive( "GF2_DollHacked", function( len, ply )
		local Entity = net.ReadEntity()
		chat.AddText(string.format(language.GetPhrase("vj_gf2_snpcs.FireWallBreached"),Entity.PrintName))
	end )
end
